### ISSUE TITLE
Night-battle-CI bug

### ISSUE THREAD

**Issue by sorewachigauyo** [poooi/plugin-report#21]
About night-battle-ci, submissions appear to be bugged/misaligned(?)
For the GTR setup there's a lot of samples with sp attack/ciType 1 (DA) when it shouldn't proc (3 slot ships)

![image](https://user-images.githubusercontent.com/26541502/49980376-2a9a6300-ff8e-11e8-86f1-fb0aeb9b7128.png)
The cutin/displayed equips aren't matching what's equipped on the ship, so I think there might be some misalignment happening

EDIT: I think that the problem might be at https://github.com/poooi/plugin-report/blob/master/reporters/night-battle-ci.es#L78

**Comment by KagamiChan** [comment]
Thanks for figuring it out

Currently I have no spare time to look into this. Do you have any suggestions for correcting it? An explanation with sample data would be helpful

**Comment by sorewachigauyo** [comment]
Could change it to `const order = api_at_list.findIndex((pos, idx) => pos === i && api_at_eflag[idx] === 0)`

Explanation
https://gist.github.com/sorewachigauyo/f48237321a81480732f663d909a45294

**Comment by KagamiChan** [comment]
ah I got it, it was variable name collision :(

**Comment by KagamiChan** [comment]
Could existing data be filtered in current situation without infecting the stat result?
If not I'll empty them

**Comment by sorewachigauyo** [comment]
pos = 0 samples are still valid

**Comment by KagamiChan** [comment]
Thanks again for resolving the bug

seems current exported data does not contain user agent field (so we cannot tell if it is from a trusted version), i'll add it. And since the data volume is more than I expected, I'll clean them

All these operations will be done in several days

**Comment by KagamiChan** [comment]
Anyway I added an `origin` field to indicate the reporter version, hopefully it could help in identifying the correct data set
