### ISSUE TITLE
向伺服器傳送通訊對象ip位址或在當通訊ip位址不符已知白名單列表時拒絕傳送？

### ISSUE THREAD

**Issue by c933103** [poooi/plugin-report#6]
記錄下來…

**Comment by yukixz** [comment]
@c933103 您想表达什么'？

**Comment by c933103** [comment]
以避免錯誤傳送其他遊戲格式相同的資料或提供更簡易的辨認方法

2016年10月21日 22:19 於 "Dazzy Ding" notifications@github.com 寫道：
